#!/bin/bash

log="/var/log/dick.log"
Percentage="2"

dft=$(df / | head -n 2 | tail -n 1 | awk '{print $5}' | sed 's/%//') 

if [ "$dft" -gt "$Percentage" ]; then

 echo "Error "$dft" " >> "$log"

fi
  





